fix remote bug
mir-dataset-loaders/mirdata pull request #352
Opened 2020-12-01 11:07 UTC by PRamoneda

sholve this #350

2020-12-01 12:39 UTC, nkundiushuti approved these changes

2020-12-11 12:26 UTC, magdalenafuentes requested changes
Looks good to me! @PRamoneda just update to master and ready to merge!

2020-12-12 12:15 UTC, magdalenafuentes commented
@PRamoneda I think the error might be because of a path issue in this line, and the index is empty?

```
        DATA = LargeData("acousticbrainz_genre_dataset_little_test.json", remote_index=REMOTE_INDEX)
```

Should it be `resources/download/acousticbrainz_genre_dataset_little_test.json`?

2020-12-12 12:59 UTC, magdalenafuentes approved these changes

2020-12-12 13:00 UTC, merged