[WIP] Adding loader for Four-Way Tabla dataset (ISMIR 21)
mir-dataset-loaders/mirdata pull request #557
Opened 2022-09-21 15:24 UTC by genisplaja

### Four-Way Tabla dataset (ISMIR 21)

### Description

Please include the following information at the top level docstring for the dataset's module mydataset.py:

- [ ] Describe annotations included in the dataset
- [ ] Indicate the size of the datasets (e.g. number files and duration, hours)
- [ ] Mention the origin of the dataset (e.g. creator, institution)
- [ ] Describe the type of music included in the dataset
- [ ] Indicate any relevant papers related to the dataset
- [ ] Include a description about how the data can be accessed and the license it uses (if applicable)

#### Dataset loaders checklist:

- [x] Create a script in `scripts/`, e.g. `make_my_dataset_index.py`, which generates an index file.
- [x] Run the script on the canonical version of the dataset and save the index in `mirdata/indexes/` e.g. `my_dataset_index.json`.
- [x] Create a module in mirdata, e.g. `mirdata/my_dataset.py`
- [x] Create tests for your loader in `tests/datasets/`, e.g. `test_my_dataset.py`
- [ ] Add your module to `docs/source/mirdata.rst` and `docs/source/quick_reference.rst`
- [ ] Run `tests/test_full_dataset.py` on your dataset.

2022-10-10 08:19 UTC, genisplaja commented
The loader is ready :) All tests are passing on my machine. Feel free to review @nkundiushuti.

2022-10-14 09:13 UTC, nkundiushuti requested changes
it looks good, maybe I would write one more test to increase test coverage.

2022-10-14 09:13 UTC, nkundiushuti commented on mirdata/datasets/four_way_tabla.py
> +    def load_audio(self, *args, **kwargs):
this looks like it was not covered by tests. can you do a test_load_audio as here:
https://github.com/mir-dataset-loaders/mirdata/blob/master/tests/datasets/test_cante100.py

2022-10-14 09:13 UTC, nkundiushuti commented on mirdata/datasets/four_way_tabla.py
> +    def load_onsets(self, *args, **kwargs):
weirdly this also looks not covered by tests although I see that you do test load_onsets in test_get_onsets

2022-10-24 11:05 UTC, genisplaja commented
Hey @nkundiushuti :) I just removed these definitions here, everything looks like it's working fine, and the coverage problem has been solved. I guess the loader would be ready now!

2022-10-26 16:51 UTC, harshpalan approved these changes
Hello @genisplaja, thanks for contributing to mirdata. I'm approving this request. @nkundiushuti Please go ahead with the review and merge. Thanks :)

2022-10-27 14:13 UTC, nkundiushuti approved these changes

2022-10-27 15:03 UTC, merged