[WIP] Zenodo Remote Migration
mir-dataset-loaders/mirdata pull request #632
Opened 2024-10-15 18:40 UTC by tanmayy24

2024-10-22 17:22 UTC, guillemcortes commented
Hi @tanmayy24 ! We've been checking the PR with @genisplaja and we believe that we should replicate the changes done in Soundata (PR: https://github.com/soundata/soundata/pull/169/) this includes the following pending changes (even though there might be other that we missed):

- [ ] Modify [get_index()](https://github.com/mir-dataset-loaders/mirdata/blob/master/mirdata/core.py#L828) as in soundata (basically remote indexes are stored in the same folder as now)
- [ ] Edit the [_index()](https://github.com/mir-dataset-loaders/mirdata/blob/master/mirdata/core.py#L165-L179) as done in soundata:
- [ ] We actually updated the whole [Index class](https://github.com/mir-dataset-loaders/mirdata/blob/master/mirdata/core.py#L785), which accommodates the remote index strategy by default :)
- [ ] [download_utils()](https://github.com/soundata/soundata/pull/169/files#diff-02ce267be2c8dcefea38790e289c80901bd57da201f59b037068db58a42ac422R111) → Check and mimic diff file in soundata PR
- [ ] Mirdata __init__ → [list_dataset_versions](https://github.com/soundata/soundata/pull/169/files#diff-733ccc06de7e4ba93fa977c272d0ec55b4c6bcd51f36c3c0fa68de88fb1d68eaR25)
- [ ] Check changes introduced in [test_download_utils()](https://github.com/soundata/soundata/pull/169/files#diff-101c3fcedeaf4478c49ae8e4c0574bff921ab86a03e2ed0004b80051eb941c23R7), [test_core() ](https://github.com/soundata/soundata/pull/169/files#diff-938de46e643ab091cff6a7c23e4e752e8907e2266f47889d988923352f7a1058R191), [test_loaders()](https://github.com/soundata/soundata/pull/169/files#diff-dd20c22fe08d50ff344daf4497a4330cdd0ee4a8c368232c140a15293bff2981R381) and mimic them
- [ ] Move sample indexes to tests folder as in soundata

2024-10-31 17:54 UTC, genisplaja reviewed
Hey @tanmayy24! That looks good, couldn't really find much problems around, just a few missing things to update!

download_utils.py, lines 96-100 should be:
```
if index.remote:
    if remotes is None:
        remotes = {}
    remotes["index"] = index.remote
```
--> DONE
I can also see that we changed lines 106 and 107 of this same file for:
```
 if remotes is not None:
        if partial_download is not None:
```
I wonder if here is any problem with that...

What about that: https://github.com/soundata/soundata/blob/b1ede7e252a9e73dc93e7b31c48c3ae10ba88532/soundata/core.py#L726. Maybe we should for now automatically set this variable to:
```
os.path.join(
    os.path.dirname(os.path.dirname(os.path.realpath(__file__))),
    "tests",
     "indexes",
)
```
Should be updated in https://github.com/mir-dataset-loaders/mirdata/pull/641

2024-11-01 09:43 UTC, guillemcortes commented
It would be great to double check with what we did in Soundata to make sure we are not missing anything. Here's the TODO list of that PR. I think that we are missing all the changes in the documentation, for instance.
https://github.com/soundata/soundata/pull/169#issuecomment-2107207637

2024-11-01 10:16 UTC, guillemcortes commented on mirdata/datasets/gtzan_genre.py
> +        url="https://zenodo.org/records/13993311/files/gtzan_genre_index_1.0.json?download=1",
why not maintain the partial download?

2024-11-01 16:28 UTC, guillemcortes requested changes
Hi! I've finished doing a first review of the PR. There are some things that need to be addressed. Luckily, most of it is copy-pasting from Soundata :)

Also, I see that you are working on a fork of mirdata. Maybe you could give write (push) access to Genís and myself so we can contribute to this PR and help a bit with all the changes.

I leave herethe things that need to be done:

- [X ] Update [pull request template](https://github.com/mir-dataset-loaders/mirdata/blob/master/.github/PULL_REQUEST_TEMPLATE/new_loader.md) with new pipeline. (As in [Soundata](https://github.com/soundata/soundata/pull/169/files#diff-ba4a34197040c325d02627fb9ddedd852f03d371ea93e29619940c53929b9becR19)) https://github.com/mir-dataset-loaders/mirdata/pull/641
- [ ] Add `soundata/datasets/indexes/*.json` to .gitignore https://github.com/mir-dataset-loaders/mirdata/pull/641
- [ ] Update [docs/index.rst](https://github.com/soundata/soundata/pull/169/files#diff-8d068e8797e88947c320f79e856c3e16a72b730124a8f9d7031e2c4680dfa534R47) https://github.com/mir-dataset-loaders/mirdata/pull/641
- [ ] Update contributing.rst (adapt from [Soundata](https://github.com/soundata/soundata/pull/169/files#diff-b4879003099a7f311a336a7c4b5d154e7009019b875c10266bad501e031ff475R26)) https://github.com/mir-dataset-loaders/mirdata/pull/641
- [ ] Update contributing_examples/example.py and contributing_examples/test_example.py https://github.com/mir-dataset-loaders/mirdata/pull/641
- [ ] Update tutorial.rst ([adapt from soundata](https://github.com/soundata/soundata/pull/169/files#diff-61c330f10c494e3e6a0b4df6f96dcc887e8204f8ddb692d93f80853b4b752bb4R40)) https://github.com/mir-dataset-loaders/mirdata/pull/641
- [ ] Update setup.py too ([follow soundata pr](https://github.com/soundata/soundata/pull/169/files#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7R12) and also consider removing the change introduced in https://github.com/mir-dataset-loaders/mirdata/pull/638/files)
- [ ] Shall we update [conftest.py](https://github.com/mir-dataset-loaders/mirdata/blob/master/tests/conftest.py) ([as in Soundata](https://github.com/soundata/soundata/pull/169/files#diff-e52e4ddd58b7ef887ab03c04116e676f6280b824ab7469d5d3080e5cba4f2128R10)) too?
- [ ] Update test_download_utils.py (check [Soundata PR](https://github.com/soundata/soundata/pull/169/files#))
- [ ] Update test_full_dataset.py (check [Soundata PR](https://github.com/soundata/soundata/pull/169/files#))
- [ ] Update test_loaders.py (check [Soundata PR](https://github.com/soundata/soundata/pull/169/files#))
- [ ] All inline and file comments of this PR that I've also written.

2024-11-01 16:28 UTC, guillemcortes commented on mirdata/download_utils.py
Same as in core.py. I leave some comments here because I cannot add an inline comment.

- [ ] L98 change it to `if remotes is None`

2024-11-01 16:28 UTC, guillemcortes commented on tests/test_core.py
> +                    "real": core.Index("acousticbrainz_genre_index_sample.json"),
We are changing the name of this index in https://github.com/mir-dataset-loaders/mirdata/pull/641/files#diff-69bfb079ff64b5be1e0fc8190bd65853a62bb32725951512bcf2536509362e40 to `acousticbrainz_genre_index_1.0_sample.json` decide what to do, if use another dataset as example, or we change it in the other PR (just a heads up so we don't forget) CC @genisplaja

2024-11-01 16:28 UTC, guillemcortes commented on tests/test_core.py
> +        local_index_path, "mirdata/datasets/", "indexes", "blah_0.json"
change this to `local_index_path, "tests", "indexes", "blah_0.json"` when we decide to move all sample indexes to tests/. CC @genisplaja

2024-11-01 16:28 UTC, guillemcortes commented on tests/test_core.py
> +        local_index_path, "mirdata/datasets/", "indexes", "blah_0.json"
Same as in line 237. CC. @genisplaja

2024-11-01 16:28 UTC, guillemcortes commented on tests/test_core.py
> +    assert dataset_real.index_path == os.path.join(
Same as in line 237. CC. @genisplaja

2024-11-01 16:28 UTC, guillemcortes commented on tests/test_core.py
- [ ] add version="sample" at initializations of L291 and L295.

2024-11-01 16:57 UTC, tanmayy24 commented on mirdata/core.py
Will be moved in the PR: https://github.com/mir-dataset-loaders/mirdata/pull/641

2024-11-01 17:02 UTC, tanmayy24 commented on mirdata/datasets/gtzan_genre.py
> +        url="https://zenodo.org/records/13993311/files/gtzan_genre_index_1.0.json?download=1",
Fixed

2024-11-01 17:12 UTC, tanmayy24 commented on mirdata/download_utils.py
Done

2024-11-03 18:24 UTC, tanmayy24 commented on tests/test_core.py
Then it wouldn't cause the dataset not found error

2024-11-03 18:34 UTC, tanmayy24 commented on mirdata/core.py
> +    def get_path(self, data_home) -> str:
done

2024-11-04 16:57 UTC, guillemcortes approved these changes
LGTM! Let's merge 🚀

2024-11-04 16:57 UTC, genisplaja approved these changes
LGTM! Thanks for that :)

2024-11-04 17:18 UTC, merged