Adding loader for SIMAC dataset
mir-dataset-loaders/mirdata pull request #636
Opened 2024-10-23 00:04 UTC by tanmayy24

Please include the following information at the top level docstring for the dataset's module mydataset.py:

- [x] Describe annotations included in the dataset
- [x] Indicate the size of the datasets (e.g. number files and duration, hours)
- [x] Mention the origin of the dataset (e.g. creator, institution)
- [x] Describe the type of music included in the dataset
- [x] Indicate any relevant papers related to the dataset
- [x] Include a description about how the data can be accessed and the license it uses (if applicable) 

#### Dataset loaders checklist:

- [x] Create a script in `scripts/`, e.g. `make_my_dataset_index.py`, which generates an index file.
- [x] Run the script on the canonical version of the dataset and save the index in `mirdata/indexes/` e.g. `my_dataset_index.json`.
- [x] Create a module in mirdata, e.g. `mirdata/my_dataset.py`
- [x] Create tests for your loader in `tests/datasets/`, e.g. `test_my_dataset.py`
- [x] Add your module to `docs/source/mirdata.rst` and `docs/source/table.rst`
- [x] Run `black`, `flake8` and `mypy` (see [Running your tests locally](https://mirdata.readthedocs.io/en/stable/source/contributing.html?highlight=contributing#running-your-tests-locally)).
- [x] Run `tests/test_full_dataset.py` on your dataset.
- [x] Check that codecov coverage does not decrease.

If your dataset **is not fully downloadable** there are two extra steps you should follow:
- [x] Contacting the mirdata organizers by opening an issue or PR so we can discuss how to proceed with the closed dataset.
- [x] Show that the version used to create the checksum is the "canonical" one, either by getting the version from the dataset creator, or by verifying equivalence with several other copies of the dataset.
- [x] Make sure someone has run `pytest -s tests/test_full_dataset.py --local --dataset my_dataset` once on your dataset locally and confirmed it passes.

#### Please-do-not-edit flag
To reduce friction, we will make commits on top of contributor's pull requests by default unless they use the `please-do-not-edit` flag. If you don't want this to happen don't forget to add the flag when you start your pull request.

2024-10-23 09:29 UTC, genisplaja requested changes
Cool :) Few minor changes but looks good.

2024-10-23 09:29 UTC, genisplaja commented on tests/datasets/test_simac.py
> +import io
maybe have that on top of the file with the rest of the imports?

2024-10-23 09:29 UTC, genisplaja commented on mirdata/datasets/simac.py
> +        tempo_path (srt): path to tempo file
`srt` --> `str`

2024-10-23 09:29 UTC, genisplaja commented on mirdata/datasets/simac.py
> +"""SIMAC Dataset Loader
how about naming it `SIMAC Rhythm Dataset` here as well?

2024-10-23 09:29 UTC, genisplaja commented on mirdata/datasets/simac.py
> +    - **Music Similarity:** SIMAC tackles the challenge of defining music similarity, considering both audio-based aspects and cultural background. It aims to develop similarity metrics that incorpor
now... maybe there is no need to describe all SIMAC features here if these are not available in the loader, it may be confusing to users. I think it's nice to mention that the SIMAC project includes all of these things, but maybe there is no need to list them all at the same level of detail as the rhythmic features, since it may make users to think that these are available.

2024-10-23 09:29 UTC, genisplaja commented on mirdata/datasets/simac.py
> +    Unfortunately most of the simac dataset is not available for download.
As suggesed for #634, it'd be a bit more conscise on what `most of the` means here.

2024-10-23 09:29 UTC, genisplaja commented on mirdata/datasets/simac.py
> +    """Load a Ballroom audio file.
`Ballroom` --> `SIMAC Rhythm`

2024-10-31 14:25 UTC, genisplaja approved these changes
Alright, I am approving this PR, please @tanmayy24 if you could update what I did suggest in this final review and I think this is ready to go :)

2024-10-31 14:25 UTC, genisplaja commented on mirdata/datasets/simac.py
> +    SIMAC identifies areas for future exploration, such as incorporating musical facets beyond timbre in similarity metrics and addressing the limitations of current approaches to similarity. The pro
Hey @tanmayy24, just a minor thing and in my opinion the loader is ready to go :) Since the project is from 2005, maybe this `Future directions and challenges` section is a little bit out of date, since we are already way beyond the future they are referring to, right? I think I'd remove this section and explicity explain that although SIMAC consider many modalities, this loader only supports the rhythmic portion of the corpora, and that we might be adding other modalities into the loader at some point (is that true?). Does that sound good?

2024-10-31 17:23 UTC, tanmayy24 commented on mirdata/datasets/simac.py
> +    SIMAC identifies areas for future exploration, such as incorporating musical facets beyond timbre in similarity metrics and addressing the limitations of current approaches to similarity. The pro
Thank you for your suggestion, I have updated the PR based on that! :)

2024-10-31 17:25 UTC, genisplaja approved these changes
Great :) Thanks!!!!

2024-10-31 17:36 UTC, merged